version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    labels:
      - "dependencies"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
