version: "3"

services:
  noisedash:
    image: noisedash/noisedash:latest
    container_name: noisedash
    ports:
      - "1432:1432"
    volumes:
      - db:/var/noisedash/db
      - samples:/var/noisedash/samples
      - ./config:/var/noisedash/config

volumes:
  db:
  samples:

